<div class="footer">
    <p>PAYMENT SHOULD BE MADE AT THE REVENUE OFFICE OR 
        TO THE REVENUE OFFICER OF THE ASSEMBLY ON OR BEFORE <?=date("Y-m-d",$result->payment_due_date)?>. FAILURE TO DO SO, 
        PROCEEDINGS WILL BE TAKEN FOR THE PURPOSE OF EXACTING SALE OR ENTRY INTO POSSESSION AND THE EXPENSES INCURRED
    </p>
</div>